name: Typing issue
description: Please use https://forms.gle/oXgwbqzvSyVHNBSc7 for reporting typing issues
title: 'Typing issue: '

body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please use the Google Form for reporting typing issues.
        >
        > https://forms.gle/oXgwbqzvSyVHNBSc7
        >
        > The
        > [reports](https://docs.google.com/spreadsheets/d/1AAK8wiTfIhj339Rb98lIRwgGfHndVz-jFXFNXZNQyeo/pubhtml?gid=649291758&single=true)
        > will be updated in 10 mins.
        >
        > See https://github.com/google/mozc/issues/1056

  - type: input
    id: na
    attributes:
      label: 'N/A'
      placeholder: Do not use this field.
    validations:
      required: true
